from django import forms
from django.forms import ModelForm, NumberInput, ModelChoiceField, RadioSelect
from .models import Golfscore, GolfCourses, Signup
from django.utils.safestring import mark_safe

class HorizontalRadioSelect(forms.RadioSelect):
  template_name = 'horizontal_select.html'

class PostForm(forms.ModelForm):

    class Meta:
        model = Golfscore
        fields = ('score1','drive1', 'longiron1', 'approach1', 'chip1', 'putt1',
         'score2','drive2', 'longiron2', 'approach2', 'chip2', 'putt2',
         'score3','drive3', 'longiron3', 'approach3', 'chip3', 'putt3',
         'score4','drive4', 'longiron4', 'approach4', 'chip4', 'putt4',
         'score5','drive5', 'longiron5', 'approach5', 'chip5', 'putt5',
         'score6','drive6', 'longiron6', 'approach6', 'chip6', 'putt6',
         'score7','drive7', 'longiron7', 'approach7', 'chip7', 'putt7',
         'score8','drive8', 'longiron8', 'approach8', 'chip8', 'putt8',
         'score9','drive9', 'longiron9', 'approach9', 'chip9', 'putt9',
         'score10','drive10', 'longiron10', 'approach10', 'chip10', 'putt10',
         'score11','drive11', 'longiron11', 'approach11', 'chip11', 'putt11',
         'score12','drive12', 'longiron12', 'approach12', 'chip12', 'putt12',
         'score13','drive13', 'longiron13', 'approach13', 'chip13', 'putt13',
         'score14','drive14', 'longiron14', 'approach14', 'chip14', 'putt14',
         'score15','drive15', 'longiron15', 'approach15', 'chip15', 'putt15',
         'score16','drive16', 'longiron16', 'approach16', 'chip16', 'putt16',
         'score17','drive17', 'longiron17', 'approach17', 'chip17', 'putt17',
         'score18','drive18', 'longiron18', 'approach18', 'chip18', 'putt18',
         'opponent1', 'opponent2', 'opponent3', 'o1totalscore', 'o2totalscore', 'o3totalscore',
         )
        widgets = {
            'score1': NumberInput(attrs={'class': 'classybox'}),
            'score2': NumberInput(attrs={'class': 'classybox'}),
            'score3': NumberInput(attrs={'class': 'classybox'}),
            'score4': NumberInput(attrs={'class': 'classybox'}),
            'score5': NumberInput(attrs={'class': 'classybox'}),
            'score6': NumberInput(attrs={'class': 'classybox'}),
            'score7': NumberInput(attrs={'class': 'classybox'}),
            'score8': NumberInput(attrs={'class': 'classybox'}),
            'score9': NumberInput(attrs={'class': 'classybox'}),
            'score10': NumberInput(attrs={'class': 'classybox'}),
            'score11': NumberInput(attrs={'class': 'classybox'}),
            'score12': NumberInput(attrs={'class': 'classybox'}),
            'score13': NumberInput(attrs={'class': 'classybox'}),
            'score14': NumberInput(attrs={'class': 'classybox'}),
            'score15': NumberInput(attrs={'class': 'classybox'}),
            'score16': NumberInput(attrs={'class': 'classybox'}),
            'score17': NumberInput(attrs={'class': 'classybox'}),
            'score18': NumberInput(attrs={'class': 'classybox'}),
            'o1totalscore': NumberInput(attrs={'class': 'classybox'}),
            'o2totalscore': NumberInput(attrs={'class': 'classybox'}),
            'o3totalscore': NumberInput(attrs={'class': 'classybox'}),
            'drive1': HorizontalRadioSelect(),
            'longiron1': HorizontalRadioSelect(),
            'approach1': HorizontalRadioSelect(),
            'chip1': HorizontalRadioSelect(),
            'putt1': HorizontalRadioSelect(),
            'drive2': HorizontalRadioSelect(),
            'longiron2': HorizontalRadioSelect(),
            'approach2': HorizontalRadioSelect(),
            'chip2': HorizontalRadioSelect(),
            'putt2': HorizontalRadioSelect(),
            'drive3': HorizontalRadioSelect(),
            'longiron3': HorizontalRadioSelect(),
            'approach3': HorizontalRadioSelect(),
            'chip3': HorizontalRadioSelect(),
            'putt3': HorizontalRadioSelect(),
            'drive4': HorizontalRadioSelect(),
            'longiron4': HorizontalRadioSelect(),
            'approach4': HorizontalRadioSelect(),
            'chip4': HorizontalRadioSelect(),
            'putt4': HorizontalRadioSelect(),
            'drive5': HorizontalRadioSelect(),
            'longiron5': HorizontalRadioSelect(),
            'approach5': HorizontalRadioSelect(),
            'chip5': HorizontalRadioSelect(),
            'putt5': HorizontalRadioSelect(),
            'drive6': HorizontalRadioSelect(),
            'longiron6': HorizontalRadioSelect(),
            'approach6': HorizontalRadioSelect(),
            'chip6': HorizontalRadioSelect(),
            'putt6': HorizontalRadioSelect(),
            'drive7': HorizontalRadioSelect(),
            'longiron7': HorizontalRadioSelect(),
            'approach7': HorizontalRadioSelect(),
            'chip7': HorizontalRadioSelect(),
            'putt7': HorizontalRadioSelect(),
            'drive8': HorizontalRadioSelect(),
            'longiron8': HorizontalRadioSelect(),
            'approach8': HorizontalRadioSelect(),
            'chip8': HorizontalRadioSelect(),
            'putt8': HorizontalRadioSelect(),
            'drive9': HorizontalRadioSelect(),
            'longiron9': HorizontalRadioSelect(),
            'approach9': HorizontalRadioSelect(),
            'chip9': HorizontalRadioSelect(),
            'putt9': HorizontalRadioSelect(),
            'drive10': HorizontalRadioSelect(),
            'longiron10': HorizontalRadioSelect(),
            'approach10': HorizontalRadioSelect(),
            'chip10': HorizontalRadioSelect(),
            'putt10': HorizontalRadioSelect(),
            'drive11': HorizontalRadioSelect(),
            'longiron11': HorizontalRadioSelect(),
            'approach11': HorizontalRadioSelect(),
            'chip11': HorizontalRadioSelect(),
            'putt11': HorizontalRadioSelect(),
            'drive12': HorizontalRadioSelect(),
            'longiron12': HorizontalRadioSelect(),
            'approach12': HorizontalRadioSelect(),
            'chip12': HorizontalRadioSelect(),
            'putt12': HorizontalRadioSelect(),
            'drive13': HorizontalRadioSelect(),
            'longiron13': HorizontalRadioSelect(),
            'approach13': HorizontalRadioSelect(),
            'chip13': HorizontalRadioSelect(),
            'putt13': HorizontalRadioSelect(),
            'drive14': HorizontalRadioSelect(),
            'longiron14': HorizontalRadioSelect(),
            'approach14': HorizontalRadioSelect(),
            'chip14': HorizontalRadioSelect(),
            'putt14': HorizontalRadioSelect(),
            'drive15': HorizontalRadioSelect(),
            'longiron15': HorizontalRadioSelect(),
            'approach15': HorizontalRadioSelect(),
            'chip15': HorizontalRadioSelect(),
            'putt15': HorizontalRadioSelect(),
            'drive16': HorizontalRadioSelect(),
            'longiron16': HorizontalRadioSelect(),
            'approach16': HorizontalRadioSelect(),
            'chip16': HorizontalRadioSelect(),
            'putt16': HorizontalRadioSelect(),
            'drive17': HorizontalRadioSelect(),
            'longiron17': HorizontalRadioSelect(),
            'approach17': HorizontalRadioSelect(),
            'chip17': HorizontalRadioSelect(),
            'putt17': HorizontalRadioSelect(),
            'drive18': HorizontalRadioSelect(),
            'longiron18': HorizontalRadioSelect(),
            'approach18': HorizontalRadioSelect(),
            'chip18': HorizontalRadioSelect(),
            'putt18': HorizontalRadioSelect(),
        }

class gcselection(forms.Form):
    field1 = ModelChoiceField(queryset=GolfCourses.objects.order_by('course'), to_field_name="course", label='Which course did you play?', empty_label="select golf course")

class PNumber(forms.ModelForm):

    class Meta:
        model = Signup
        fields = ('phonenumber',)
